spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://27.96.135.39:3306/mydb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
#    username: root
#    password: '!My123456!'

    url: jdbc:h2:tcp://localhost/~/withsafe
    username: sa
    password: 1
    driver-class-name: org.h2.Driver

  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션
#  jpa:
#    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.orm.jdbc.bind: trace

jwt:
  secret: /vUwAz/Vx78zX5/E4v6kjfbyoTRpYtOK2WT9rYcXeNPzDMuv1BlehYL113paVVYvUTyUIYg3kSZglWjEAJxgMw==