spring:
  datasource:

      url: jdbc:h2:tcp://localhost/~/withsafe
      username: sa
      password: 1
      driver-class-name: org.h2.Driver



  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true

  jpa:
    #database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

jwt:
  secret: /vUwAz/Vx78zX5/E4v6kjfbyoTRpYtOK2WT9rYcXeNPzDMuv1BlehYL113paVVYvUTyUIYg3kSZglWjEAJxgMw==